### ISSUE TITLE
Webpage Issues - "missing" CSS

### ISSUE THREAD

**Issue by thecapacity** [WhiteHouse/software-policy#22]
I'm getting an issue when accessing: https://software.cio.gov/  

-- It looks like no CSS is being delivered, but I confirmed from the page source the CSS files are present and and valid.

<img width="1371" alt="screen shot 2016-08-16 at 1 32 09 pm" src="https://cloud.githubusercontent.com/assets/57710/17709126/efb23d42-63b5-11e6-9560-42fce54b8b4f.png">

**Comment by mattbailey0** [comment]
..and we're back. Thank you again! https://github.com/WhiteHouse/software-policy/commit/34ce6e4d022fd16d48d1ece20882b895c836a11f
