### ISSUE TITLE
HTTPS 404 Error

### ISSUE THREAD

**Issue by thecapacity** [WhiteHouse/software-policy#23]
I get a "github 404" style page not found when accessing: https://software.cio.gov/software-policy

I'm not sure if this is permissions or publication

When accessing it via http:// I am getting redirected to (the same) https:// error page.

**Comment by ghost** [comment]
@thecapacity Hi Jay I found the right link here https://software.cio.gov/ the css appears to be broken but works fine

**Comment by mattbailey0** [comment]
@thecapacity thank you for this and #22. I'm running these down. As near as I can tell this issue is just a matter of a broken link - it should link to / instead.

**Comment by mattbailey0** [comment]
Fixed - thank you again! https://github.com/WhiteHouse/software-policy/commit/34ce6e4d022fd16d48d1ece20882b895c836a11f
